spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/joboffers
offer:
  http:
    client:
      config:
        connectTimeout: 5000
        readTimeout: 5000
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
        port: 5057

http:
  offers:
    scheduler:
      request:
        delay: PT3H

scheduling:
  enabled: true