spring:
  cache:
    type: redis
    redis:
      time-to-live: PT60M
  redis:
    port: ${REDIS_PORT:63792}
    host: ${REDIS_HOST:localhost}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://admin:admin@localhost:27017/offers
offer:
  http:
    client:
      config:
        connectTimeout: 5000
        readTimeout: 5000
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
        port: 5057
auth:
  token:
    secret: ${JWT_SECRET}
    issuer: Job-Offers-Service
    expirationInDays: 30

http:
  offers:
    scheduler:
      request:
        delay: PT3H

scheduling:
  enabled: true

#logging:
#  level:
#    root: debug